export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const CHOOSE_TELEGRAM_NAME = 'CHOOSE_TELEGRAM_NAME';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const CLEAR_IS_QUESTION_ADDED = 'CLEAR_IS_QUESTION_ADDED';
export const CLEAR_SIGN_UP = 'CLEAR_SIGN_UP';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CREATE_MESSAGE_FAIL = 'CREATE_MESSAGE_FAIL';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';
export const DELETE_CATEGORIES_FAIL = 'DELETE_CATEGORIES_FAIL';
export const DELETE_CATEGORIES_SUCCESS = 'DELETE_CATEGORIES_SUCCESS'
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_FAIL = 'DELETE_QUESTION_FAIL';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const GET_ANSWERS = 'GET_ANSWERS';
export const GET_ANSWERS_FAIL = 'GET_ANSWERS_FAIL';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_RATING = 'GET_RATING';
export const GET_RATING_FAIL = 'GET_RATING';
export const GET_RATING_SUCCESS = 'GET_RATING_SUCCESS';
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ALL_QUESTIONS_FAIL = "GET_ALL_QUESTIONS_FAIL";
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_USER_EXIST = 'GET_USER_EXIST';
export const GET_USER_EXIST_SUCCESS = 'GET_USER_EXIST_SUCCESS';
export const GET_USER_EXIST_FAIL = 'GET_USER_EXIST_FAIL';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const SET_SIGN_UP = 'SET_LOGIN_IN';




